DROP SEQUENCE SQ_LTP_VEICULO;
DROP TABLE TB_LTP_VEICULO CASCADE CONSTRAINTS;
 
 CREATE TABLE TB_LTP_VEICULO ( 
    ID_VEICULO INTEGER NOT NULL,
    MODELO VARCHAR2(50) NOT NULL,
    PLACA VARCHAR2(8) NOT NULL,
    ANO VARCHAR(4) NOT NULL,
    motor decimal(2,1) not null,
    CONSTRAINT FK_LTP_VEICULO primary key (id_veiculo)
    ) SEGMENT CREATION IMMEDIATE;
  
  CREATE SEQUENCE SQ_LTP_VEICULO INCREMENT BY 1 START WITH 1 NOCYCLE ORDER;
    